server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          library-client:
            provider: okta
            client-id: 0oajbryix1d8ABX1i0h7
            client-secret: IO_t-KoGka55dz0AVx94mraOig4zclp4ri4Y92vl
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email, offline_access
        provider:
          okta:
            issuer-uri: https://dev-667216.oktapreview.com/oauth2/ausjbx4pq5Wg0kZx10h7
