server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: local-authserver
            client-id: library-client
            client-secret: secret
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope: profile
            client-name: Login Client
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          local-authserver:
            authorization-uri: http://localhost:9999/users/oauth/authorize
            token-uri: http://localhost:9999/users/oauth/token
            user-info-uri: http://localhost:9999/users/resources/userinfo
            user-name-attribute: id
